
version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  app:
    container_name: fitness-app
    restart: always
    build: ./
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    links:
      - mongo

