
version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"

  app:
    container_name: fitness-app
    restart: always
    build: ./
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - .:/app
        # This wont work when installing new node_modules
        # https://stackoverflow.com/questions/30043872/docker-compose-node-modules-not-present-in-a-volume-after-npm-install-succeeds
      # - /app/node_modules
    links:
      - mongo

